### ISSUE TITLE
ModuleNotFoundError: No module named 'mobileprovision'

### ISSUE THREAD

**Issue by Willianlike** [shede333/PyMobileProvision#1]
I have installed on mac os, but module not found.
To install i executed "sudo pip install PyMobileProvision"
To import i writed "from mobileprovision import parser" and "from PyMobileProvision import parser" but it doesn't work.
![image](https://user-images.githubusercontent.com/26646435/64159689-4a86f500-ce43-11e9-8c40-b7820f2b48ff.png)
![image](https://user-images.githubusercontent.com/26646435/64159787-6b4f4a80-ce43-11e9-8373-2195b9009c9e.png)
Can you help?

**Comment by shede333** [comment]
> I have installed on mac os, but module not found.
> To install i executed "sudo pip install PyMobileProvision"
> To import i writed "from mobileprovision import parser" and "from PyMobileProvision import parser" but it doesn't work.
> ![image](https://user-images.githubusercontent.com/26646435/64159689-4a86f500-ce43-11e9-8c40-b7820f2b48ff.png)
> ![image](https://user-images.githubusercontent.com/26646435/64159787-6b4f4a80-ce43-11e9-8373-2195b9009c9e.png)
> Can you help?

you can try "sudo python3 -m pip install PyMobileProvision"
